// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SuperBestFriends.Web.DAL;

#nullable disable

namespace SuperBestFriends.Web.Migrations
{
    [DbContext(typeof(FriendsDbContext))]
    [Migration("20240730084543_InitialTabAddress")]
    partial class InitialTabAddress
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SuperBestFriends.Web.DAL.Entities.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Interests")
                        .IsRequired()
                        .HasColumnType("ntext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1L,
                            Address = "",
                            BirthDate = new DateTime(1998, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jean.michel@gmail.com",
                            FirstName = "Jean",
                            Interests = "Blah,blah,blah",
                            LastName = "Michel",
                            PhoneNumber = "0638451475"
                        },
                        new
                        {
                            UserId = 2L,
                            Address = "",
                            BirthDate = new DateTime(1985, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "marie.dupont@yahoo.fr",
                            FirstName = "Marie",
                            Interests = "Yoga,Cuisine,Lecture",
                            LastName = "Dupont",
                            PhoneNumber = "0645789632"
                        },
                        new
                        {
                            UserId = 3L,
                            Address = "",
                            BirthDate = new DateTime(1990, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "p.durand@hotmail.com",
                            FirstName = "Pierre",
                            Interests = "Football,Cinéma,Voyages",
                            LastName = "Durand",
                            PhoneNumber = "0712345678"
                        },
                        new
                        {
                            UserId = 4L,
                            Address = "",
                            BirthDate = new DateTime(1992, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sophie.martin@gmail.com",
                            FirstName = "Sophie",
                            Interests = "Photographie,Danse,Jardinage",
                            LastName = "Martin",
                            PhoneNumber = "0698765432"
                        },
                        new
                        {
                            UserId = 5L,
                            Address = "",
                            BirthDate = new DateTime(1988, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "thomas.leroy@outlook.com",
                            FirstName = "Thomas",
                            Interests = "Musique,Technologie,Randonnée",
                            LastName = "Leroy",
                            PhoneNumber = "0623456789"
                        },
                        new
                        {
                            UserId = 6L,
                            Address = "",
                            BirthDate = new DateTime(1995, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "camille.dubois@free.fr",
                            FirstName = "Camille",
                            Interests = "Peinture,Théâtre,Natation",
                            LastName = "Dubois",
                            PhoneNumber = "0787654321"
                        },
                        new
                        {
                            UserId = 7L,
                            Address = "",
                            BirthDate = new DateTime(1987, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lucas.moreau@orange.fr",
                            FirstName = "Lucas",
                            Interests = "Jeux vidéo,Ski,Cuisine asiatique",
                            LastName = "Moreau",
                            PhoneNumber = "0634567890"
                        },
                        new
                        {
                            UserId = 8L,
                            Address = "",
                            BirthDate = new DateTime(1993, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "emma.lefebvre@gmail.com",
                            FirstName = "Emma",
                            Interests = "Mode,Fitness,Voyages",
                            LastName = "Lefebvre",
                            PhoneNumber = "0756789012"
                        },
                        new
                        {
                            UserId = 9L,
                            Address = "",
                            BirthDate = new DateTime(1991, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nicolas.roux@yahoo.com",
                            FirstName = "Nicolas",
                            Interests = "Escalade,Photographie,Histoire",
                            LastName = "Roux",
                            PhoneNumber = "0678901234"
                        },
                        new
                        {
                            UserId = 10L,
                            Address = "",
                            BirthDate = new DateTime(1989, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "chloe.girard@hotmail.fr",
                            FirstName = "Chloé",
                            Interests = "Yoga,Méditation,Cuisine végétarienne",
                            LastName = "Girard",
                            PhoneNumber = "0701234567"
                        },
                        new
                        {
                            UserId = 11L,
                            Address = "",
                            BirthDate = new DateTime(1994, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "antoine.blanc@gmail.com",
                            FirstName = "Antoine",
                            Interests = "Basket,Littérature,Astronomie",
                            LastName = "Blanc",
                            PhoneNumber = "0654321098"
                        });
                });

            modelBuilder.Entity("UserUser", b =>
                {
                    b.Property<long>("FriendsOfUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("FriendsUserId")
                        .HasColumnType("bigint");

                    b.HasKey("FriendsOfUserId", "FriendsUserId");

                    b.HasIndex("FriendsUserId");

                    b.ToTable("UserUser");
                });

            modelBuilder.Entity("UserUser", b =>
                {
                    b.HasOne("SuperBestFriends.Web.DAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("FriendsOfUserId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("SuperBestFriends.Web.DAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("FriendsUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
